// Tabela de usuários da aplicação
// Tabela dimensão
Table users {
  id SERIAL [pk, increment]
  created_at TIMESTAMP
  updated_at TIMESTAMP
  username VARCHAR(30)
}

// Tabela de publicações (fotos)
// Tabela fato
Table posts {
  id SERIAL [pk, increment]
  created_at TIMESTAMP
  updated_at TIMESTAMP
  url VARCHAR(200)
  user_id INTEGER
  caption VARCHAR(240)
  lat REAL
  lng REAL
}

// Tabela de comentários 
// Tabela fato
Table comments {
  id SERIAL [pk, increment]
  created_at TIMESTAMP
  updated_at TIMESTAMP
  contents VARCHAR(240)
  user_id INTEGER
  post_id INTEGER
}

// Tabela de likes (curtidas)
// Tabela fato
Table likes {
  id SERIAL [pk, increment]
  created_at TIMESTAMP
  user_id INTEGER
  post_id INTEGER
  comment_id INTEGER
}

// Tabela de tags em publicações (uma tag é uma menção a outro usuário da aplicação)
// Tabela fato
Table post_tags {
  id SERIAL [pk, increment]
  created_at TIMESTAMP
  updated_at TIMESTAMP
  user_id INTEGER
  post_id INTEGER
  x INTEGER
  y INTEGER
}

// Tabela de tags em legendas
// Tabela fato
Table caption_tags {
  id SERIAL [pk, increment]
  created_at TIMESTAMP
  user_id INTEGER
  post_id INTEGER
}

// Tabela de hashtags
// Tabela dimensão
Table hashtags {
  id SERIAL [pk, increment]
  created_at TIMESTAMP
  title VARCHAR(20)
}

// Tabela de hashtags em publicações
// Tabela fato
Table hashtags_posts {
  id SERIAL [pk, increment]
  hashtag_id INTEGER
  post_id INTEGER
}

// Um usuário pode ter muitas publicações
Ref {
  users.id < posts.user_id
}

// Um usuário pode escrever muitos comentários
Ref {
  users.id < comments.user_id
}

// Uma publicação pode ter muitos comentários
Ref {
  post.id < comments.post_id
}

// Um usuário pode curtir muitas publicações e/ou comentários
Ref {
  users.id < likes.user_id
}

// Uma publicação pode receber muitas curtidas
Ref {
  posts.id < likes.post_id
}

// Um comentário pode receber muitas curtidas
Ref {
  comments.id < likes.comment_id
}

// Um usuário pode ser mencionado muitas vezes
Ref {
  users.id < post_tags.user_id
}

// Uma publicação pode conter muitas menções
Ref {
  posts.id < post_tags.post_id
}

// Um usuário pode ser mencionado muitas vezes numa legenda
Ref {
  users.id < caption_tags.user_id
}

// Uma publicação pode conter muitas menções na legenda
Ref {
  posts.id < caption_tags.post_id
}

Ref {
  hashtags.id < hashtags_posts.hashtag_id
}

// Uma hashtag pode ser usada muitas vezes dentro de uma publicação
Ref {
  posts.id < hashtags_posts.post_id
}